name: flutter_testes_unitarios
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

vars:
  coverage_info: coverage/lcov.info
  ignore_files: '**/*.g.dart' 
scripts:
  auto_format: dartfmt -w .
  test: flutter test --coverage test/
  gen_coverage: lcov --remove $coverage_info $ignore_files -o $coverage_info & genhtml $coverage_info -o coverage/html

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3

flutter:
  uses-material-design: true